version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - angia-network

networks:
  angia-network:
    external: true
    name: angia-website_angia-network
