version: "3"
services:
  portfolio:
    build: .
    container_name: my-portfolio
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - web

networks:
  web:
    external: true
