version: "3.8"

services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`michael.angia.com.au`)"

networks:
  web:
    external: true
