version: "3.8"

services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - angia-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`michael.angia.com.au`)"

networks:
  angia-network:
    external:
      name: angia-website_angia-network
