version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
        - nginx:alpine
    container_name: portfolio
    restart: unless-stopped
    networks:
      - angia-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`michael.angia.com.au`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.docker.network=angia-website_angia-network"

networks:
  angia-network:
    external:
      name: angia-website_angia-network
