// All paths now start from root
const images = {
  // Background image
  code: "/images/code.png",

  // Skills Images
  javaScriptLogo: "/images/javaScriptLogo.png",
  reactLogo: "/images/reactLogo.png",
  typeScriptLogo: "/images/typeScriptLogo.png",
  htmlLogo: "/images/htmlLogo.png",
  tailwindCssLogo: "/images/tailwindCssLogo.png",
  sassLogo: "/images/sassLogo.png",
  nodeLogo: "/images/node.png",
  gitLogo: "/images/gitLogo.png",
  figmaLogo: "/images/figmaLogo.png",
  cssLogo: "/images/cssLogo.png",
  awsLogo: "/images/awsLogo.png",
  sqLite: "/images/sqLite.png",
  slack: "/images/slack.png",
  graphQL: "/images/graphQL.png",
  linkedIn: "/images/linkedIn.png",
  databaseSchema: "/images/databaseSchema.png",

  // Personal Images
  waterBackground: "/images/waterBackground.jpeg",
  personal1: "/images/personal1.jpeg",
  profilePic: "/images/profilePic.png",
  flyboarding: "/images/flyboarding.gif",

  // Projects
  jobPlusHomeBig: "/images/jobPlusHomeBig.png",
  jobPlusHomeSmall: "/images/jobPlusHomeSmall.png",
  jobPluListingBig: "/images/jobPlusListingBig.png",
  jobPlusListingSmall: "/images/jobPlusListingSmall.png",
  jobPlusRegBig: "/images/jobPlusRegBig.png",
  jobPlusRegSmall: "/images/jobPlusRegSmall.png",
  bookerDashBig: "/images/bookerDashBig.png",
  bookerCheckoutBig: "/images/bookerCheckoutBig.png",
  bookerCheckoutSmall: "/images/bookerCheckoutSmall.png",
  bookerDashSmall: "/images/bookerDashSmall.png",
  bookerHomeBig: "/images/bookerHomeBig.png",
  bookerHomeSmall: "/images/bookerHomeSmall.png",
  bookerFinBig: "/images/bookerFinBig.png",
  bookerFinSmall: "/images/bookerFinSmall.png",
  bookerBookingsBig: "/images/bookerBookingsBig.png",
  bookerBookingsSmall: "/images/bookerBookingsSmall.png",
  butcherBig: "/images/butcherBig.png",
  butcherSmall: "/images/butcherSmall.png",
  kineticSmall: "/images/kineticSmall.png",
  kineticBig: "/images/kineticBig.png",

  // GIFs
  Admin1Gif: "/images/jobplusAdmin2.gif",
  Admin2Gif: "/images/jobplusAdmin1.gif",
  jobplusFrontend1: "/images/jobplusFrontend1.gif",

  // Community outreach
  covid1: "/images/covid1.png",
  covid2: "/images/covid2.png",
  marikina2: "/images/marikina2.jpeg",
  marikina3: "/images/marikina3.jpeg",
  marikina4: "/images/marikina4.jpeg",
  marikina5: "/images/marikina5.jpeg",
  saintRita1: "/images/saintRita1.png",
  saintRita2: "/images/saintRita2.png",
  saintRita3: "/images/saintRita3.png",
  saintRita4: "/images/saintRita4.png",
};

export const {
  linkedIn,
  code,
  javaScriptLogo,
  reactLogo,
  typeScriptLogo,
  htmlLogo,
  tailwindCssLogo,
  sassLogo,
  nodeLogo,
  gitLogo,
  figmaLogo,
  cssLogo,
  awsLogo,
  slack,
  sqLite,
  graphQL,
  databaseSchema,
  waterBackground,
  personal1,
  profilePic,
  flyboarding,
  jobPlusHomeBig,
  jobPlusHomeSmall,
  jobPluListingBig,
  jobPlusListingSmall,
  jobPlusRegBig,
  jobPlusRegSmall,
  bookerCheckoutBig,
  bookerCheckoutSmall,
  bookerDashBig,
  bookerDashSmall,
  bookerFinBig,
  bookerFinSmall,
  bookerHomeBig,
  bookerHomeSmall,
  bookerBookingsBig,
  bookerBookingsSmall,
  butcherBig,
  butcherSmall,
  jobplusFrontend1,
  Admin1Gif,
  Admin2Gif,
  kineticBig,
  kineticSmall,
  covid1,
  covid2,
  marikina2,
  marikina3,
  marikina4,
  marikina5,
  saintRita1,
  saintRita2,
  saintRita3,
  saintRita4,
} = images;
