name: Deploy to Production

on:
  push:
    branches: [main]

env:
  REPO_NAME: my-portfolio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
          echo "ServerAliveInterval 60" >> ~/.ssh/config
          echo "ServerAliveCountMax 10" >> ~/.ssh/config

      - name: Deploy to Digital Ocean
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 root@$DROPLET_IP << 'ENDSSH'
            set -e  # Exit on error
            
            # Navigate to project directory
            echo "Navigating to project directory..."
            cd /root/my-portfolio
            
            # Update code
            echo "Pulling latest changes..."
            git pull origin main
            
            # Clean up Docker resources
            echo "Cleaning up Docker resources..."
            docker system prune -f
            
            # Build and start the application with increased timeout
            echo "Starting application..."
            export COMPOSE_HTTP_TIMEOUT=300
            docker-compose down || true
            docker-compose build --no-cache
            docker-compose up -d
            
            echo "Deployment completed successfully!"
          ENDSSH
